In [1]:
from pickletools import float8
from typing import Any

import numpy as np
from numpy.ma.core import shape

# array1 = np.random.randint(1, 100, size=(10, 5))  # row/sample - 10, column/feature - 5
array1 = np.array(
    [
        [38, 76, 84, 54, 70],
        [12, 31, 77, 35, 56],
        [12, 85, 48, 37, 89],
        [19, 22, 53, 97, 4],
        [63, 80, 87, 67, 29],
        [2, 93, 16, 91, 99],
        [60, 62, 18, 80, 66],
        [70, 90, 77, 8, 44],
        [86, 5, 33, 63, 67],
        [6, 98, 79, 86, 72]
    ]
)  # row/sample - 10 , column/feature - 5

print(array1)
print(array1.shape)
print(array1.dtype)
print(array1.ndim)
print(array1.size)



# Reshape: To reshape an array, we must keep the size of the array completely the same, otherwise we will get an error. Combining row wise.
array2 = array1.reshape(5, 10)
print(array2)
print(array2.shape)
print(array2.ndim)



# Converting the array from dimension 2 to dimension 1. 2D to 1D. Combining row wise.
array3 = array2.flatten()
print(array3)
print(array3.shape)
print(array3.ndim)



# To conver the array from dimension 2 to dimension 1, but combining column wise.
# array4 = array2.ravel(order="F")
array4 = np.ravel(array2, order="F")        # F = Column-wise, C = Row-wise
print(array4)
print(array4.shape)
print(array4.ndim)

[[38 76 84 54 70]
 [12 31 77 35 56]
 [12 85 48 37 89]
 [19 22 53 97  4]
 [63 80 87 67 29]
 [ 2 93 16 91 99]
 [60 62 18 80 66]
 [70 90 77  8 44]
 [86  5 33 63 67]
 [ 6 98 79 86 72]]
(10, 5)
int64
2
50
[[38 76 84 54 70 12 31 77 35 56]
 [12 85 48 37 89 19 22 53 97  4]
 [63 80 87 67 29  2 93 16 91 99]
 [60 62 18 80 66 70 90 77  8 44]
 [86  5 33 63 67  6 98 79 86 72]]
(5, 10)
2
[38 76 84 54 70 12 31 77 35 56 12 85 48 37 89 19 22 53 97  4 63 80 87 67
 29  2 93 16 91 99 60 62 18 80 66 70 90 77  8 44 86  5 33 63 67  6 98 79
 86 72]
(50,)
1
[38 12 63 60 86 76 85 80 62  5 84 48 87 18 33 54 37 67 80 63 70 89 29 66
 67 12 19  2 70  6 31 22 93 90 98 77 53 16 77 79 35 97 91  8 86 56  4 99
 44 72]
(50,)
1


# Concatenate

In [2]:
# array5 = np.random.randint(1, 10, size=(2, 3))    # row 2, column 3
array5 = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)


# array6 = np.random.randint(20, 30, size=(2, 3))   # row 2, column 3
array6 = np.array(
    [
        [21, 22, 23],
        [24, 25, 26]
    ]
)


print(array5)
print(array6)
print(array5.shape)
print(array6.shape)

[[1 2 3]
 [4 5 6]]
[[21 22 23]
 [24 25 26]]
(2, 3)
(2, 3)


In [3]:
# Concatenation can only be done if the shapes match,
# To concatenate two arrays, they must have the same number of dimensions.
# To concatenate row wise, the number of columns in the first array must be equal to the number of columns in the second array.
# To concatenate column wise, the number of rows in the first array must be equal to the number of rows in the second array.


# Row-wise concatenation
array5_concat_array6_row = np.concatenate((array5, array6), axis=0)
print(array5_concat_array6_row)


# Column-wise concatenation
array5_concat_array6_col = np.concatenate((array5, array6), axis=1)
print(array5_concat_array6_col)


[[ 1  2  3]
 [ 4  5  6]
 [21 22 23]
 [24 25 26]]
[[ 1  2  3 21 22 23]
 [ 4  5  6 24 25 26]]


# Transpose

In [4]:
matrix1 = np.array(
    [
        [10, 20, 30],
        [40, 50, 60]
    ]
)
print(matrix1)


# Transpose the matrix1
matrix1_transposed = matrix1.T
print(matrix1_transposed)

[[10 20 30]
 [40 50 60]]
[[10 40]
 [20 50]
 [30 60]]


# Array Splitting

In [5]:
# array7 = np.random.randint(1, 10, size=(1, 30))    # row 1, column 10
array7 = np.array([4, 6, 8, 1, 9, 4, 3, 9, 9, 1, 4, 2, 8, 9, 7, 4, 3, 1, 2, 6, 7, 9, 3, 3, 1, 2, 7, 7, 8, 8])
print(array7)



# Splitting the array into 3 equal slices
array7_split_equal = np.split(array7, 3)
print(array7_split_equal)



# Splitting the array into 4 not-equal slices along the rows
array7_split_nequal = np.array_split(array7, 4)
print(array7_split_nequal)


[4 6 8 1 9 4 3 9 9 1 4 2 8 9 7 4 3 1 2 6 7 9 3 3 1 2 7 7 8 8]
[array([4, 6, 8, 1, 9, 4, 3, 9, 9, 1]), array([4, 2, 8, 9, 7, 4, 3, 1, 2, 6]), array([7, 9, 3, 3, 1, 2, 7, 7, 8, 8])]
[array([4, 6, 8, 1, 9, 4, 3, 9]), array([9, 1, 4, 2, 8, 9, 7, 4]), array([3, 1, 2, 6, 7, 9, 3]), array([3, 1, 2, 7, 7, 8, 8])]


# Arithmetic operator and mathematical functions
These operations are done by vectorization, not by looping through each element. Therefore the operations are superfast.

In [6]:
array8 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(array8)
print(array8.shape)



array9 = np.array([1, 2, 3, 5, 6, 7, 8, 9, 10, 11])
print(array9)
print(array9.shape)

[ 10  20  30  40  50  60  70  80  90 100]
(10,)
[ 1  2  3  5  6  7  8  9 10 11]
(10,)


In [7]:
# Adding two arrays
# For this, the shapes of the two arrays must be the same


# array8plus9 = array8 + array9
array8plus9 = np.add(array8, array9)
print(array8plus9)

[ 11  22  33  45  56  67  78  89 100 111]


In [8]:
# Subtracting two arrays


# array8minus9 = array8 - array9
array8minus9 = np.subtract(array8, array9)
print(array8minus9)

[ 9 18 27 35 44 53 62 71 80 89]


In [9]:
# Multiplying two arrays


# array8times9 = array8 * array9
array8times9 = np.multiply(array8, array9)
print(array8times9)

[  10   40   90  200  300  420  560  720  900 1100]


In [10]:
# Division of two arrays


# array8div9 = array8 / array9
array8div9 = np.divide(array8, array9)
print(array8div9)

[10.         10.         10.          8.          8.33333333  8.57142857
  8.75        8.88888889  9.          9.09090909]


In [11]:
# Remainder of two arrays


# array8mod9 = array8 % array9
array8mod9 = np.mod(array8, array9)
print(array8mod9)

[0 0 0 0 2 4 6 8 0 1]


# Trigonometry

In [12]:
print(array8)


# Sin values of array8 elements, all these values are in radians
array8_sin = np.sin(array8)
print(array8_sin)



# Cos values of array8 elements, all these values are in radians
array8_cos = np.cos(array8)
print(array8_cos)



# Tan values of array8 elements, all these values are in radians
array8_tan = np.tan(array8)
print(array8_tan)

[ 10  20  30  40  50  60  70  80  90 100]
[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485 -0.30481062
  0.77389068 -0.99388865  0.89399666 -0.50636564]
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603 -0.95241298
  0.6333192  -0.11038724 -0.44807362  0.86231887]
[ 0.64836083  2.23716094 -6.4053312  -1.11721493 -0.27190061  0.32004039
  1.22195992  9.00365495 -1.99520041 -0.58721392]


# Converting radian values into degree values.
* Theoretically,  degreeValues = radianValues * (180/pi)

In [13]:
array8_sin_rad2deg = np.rad2deg(array8_sin)
print(array8_sin_rad2deg)


array8_cos_rad2deg = np.rad2deg(array8_cos)
print(array8_cos_rad2deg)


array8_tan_rad2deg = np.rad2deg(array8_tan)
print(array8_tan_rad2deg)

[-31.17011362  52.30790979 -56.61004209  42.69183936 -15.03297177
 -17.46436214  44.34066986 -56.94562518  51.22223572 -29.01261413]
[-48.07525733  23.38137984   8.83795706 -38.21273613  55.28848081
 -54.56924413  36.28651742  -6.32472318 -25.67272712  49.40723198]
[  37.14833902  128.1798802  -366.99844395  -64.01170035  -15.57875751
   18.33696359   70.01314604  515.87142858 -114.3165629   -33.64487901]


# Converting degree values into radian values.
* Theoretically,  radianValues = degreeValues * (pi/180)

In [14]:
array8_sin_deg2rad = np.deg2rad(array8_sin_rad2deg)
print(array8_sin_deg2rad)


array8_cos_deg2rad = np.rad2deg(array8_cos_rad2deg)
print(array8_cos_deg2rad)


array8_tan_deg2rad = np.rad2deg(array8_tan_rad2deg)
print(array8_tan_deg2rad)

[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485 -0.30481062
  0.77389068 -0.99388865  0.89399666 -0.50636564]
[-2754.50934377  1339.65438385   506.37763919 -2189.42850386
  3167.79660588 -3126.58737994  2079.06430148  -362.37994504
 -1470.9389123   2830.82586968]
[  2128.44304148   7344.1661537  -21027.46192628  -3667.60026956
   -892.59705564   1050.63062252   4011.45777872  29557.25562875
  -6549.85658274  -1927.70956949]


# Converting the array elements into base 10 log values
* লগারিদম আসলে বোঝায় ১০-এর পাওয়ার (Power) কত হলে ওই সংখ্যাটি পাওয়া যাবে। সহজভাবে বললে: 10^x = সংখ্যা। এখানে x হলো সেই সংখ্যার log_10 ভ্যালু।

In [15]:
array10 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(array10)


array10_base10log = np.log10(array10)
print(array10_base10log)

# অর্থাৎ, ১০ কে ১.৩০১০৩ বার গুণ করলে (গাণিতিক সূচকের নিয়মে) আপনি ২০ পাবেন।

[ 10  20  30  40  50  60  70  80  90 100]
[1.         1.30103    1.47712125 1.60205999 1.69897    1.77815125
 1.84509804 1.90308999 1.95424251 2.        ]


# Converting the array elements into base 2 log values
* লগারিদম (Base 2) আসলে বোঝায় ২-এর পাওয়ার (Power) কত হলে ওই সংখ্যাটি পাওয়া যাবে। সহজভাবে বললে: 2^x = সংখ্যা। এখানে x হলো সেই সংখ্যার log_2 ভ্যালু।

In [16]:
print(array10)


array10_base2log = np.log2(array10)
print(array10_base2log)

[ 10  20  30  40  50  60  70  80  90 100]
[3.32192809 4.32192809 4.9068906  5.32192809 5.64385619 5.9068906
 6.12928302 6.32192809 6.4918531  6.64385619]


# Square

In [17]:
print(array9)
array9_square = np.square(array9)
print(array9_square)

[ 1  2  3  5  6  7  8  9 10 11]
[  1   4   9  25  36  49  64  81 100 121]


# Square root

In [18]:
print(array10)
array10_sqrt = np.sqrt(array10)
print(array10_sqrt)

[ 10  20  30  40  50  60  70  80  90 100]
[ 3.16227766  4.47213595  5.47722558  6.32455532  7.07106781  7.74596669
  8.36660027  8.94427191  9.48683298 10.        ]


# Total sum

In [19]:
print(array9)

array9_sum = np.sum(array9)
print(array9_sum)

[ 1  2  3  5  6  7  8  9 10 11]
62


# Cumulative sum

In [20]:
print(array9)

# array9_cum_sum = np.cumulative_sum(array9)
array9_cum_sum = np.cumsum(array9)
print(array9_cum_sum)

[ 1  2  3  5  6  7  8  9 10 11]
[ 1  3  6 11 17 24 32 41 51 62]


In [21]:
rows = 1
cols = 4
arraySerial = np.arange(1, rows * cols + 1).reshape(rows, cols)
print(arraySerial)

[[1 2 3 4]]


# Broadcasting

In [22]:
print(array9)


array9_broadcasting1 = array9 ** 2
print(array9_broadcasting1)


array9_broadcasting2 = array9 + 2
print(array9_broadcasting2)


matrix2 = np.array(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8]
    ]
)
matrix2_broadcasting = matrix2 * 2
print(matrix2_broadcasting)


vector1 = np.array([1, 2, 3, 4])
# print(vector1)


vector_matrix_broadcasting = vector1 * matrix2
print(vector_matrix_broadcasting)

[ 1  2  3  5  6  7  8  9 10 11]
[  1   4   9  25  36  49  64  81 100 121]
[ 3  4  5  7  8  9 10 11 12 13]
[[ 2  4  6  8]
 [10 12 14 16]]
[[ 1  4  9 16]
 [ 5 12 21 32]]


* #### To lear more, visit: https://numpy.org/doc/2.4/reference/routines.math.html

# Logical Function

In [23]:
# comparison - >,< , >= ,<= , == , !=

array10 = np.array([ 10 , 8 , 16 , 100 ])
array11 = np.array([ 2 , 3 ,16  ,5 ])


greater_than = array10 > array11
print(greater_than)


equal = array10 == array11
print(equal)


print(np.all(greater_than))         # It checks if all the elements of the array are true, otherwise it returns false.
print(np.any(greater_than))         # It checks if at least one element of the array is true, otherwise it returns false.


print(np.all(equal))                # It checks if all the elements of the array are equal, otherwise it returns false.
print(np.any(equal))                # It checks if at least one element of the array is equal, otherwise it returns false.

[ True  True False  True]
[False False  True False]
False
True
False
True


# Sorting

In [24]:
# Inplace sorting: that means the original array will be sorted in place and then the sorted array is returned if we don't use a copy of the original array.


# arrayRandom = np.random.randint(1, 100, size=(1, 10))    # row 2, column 3
array12 = np.array([[82, 53, 9, 34, 11, 23, 48, 23, 26, 12]])
print(array12)


array12_sorted = np.sort(array12)
print(array12_sorted)

[[82 53  9 34 11 23 48 23 26 12]]
[[ 9 11 12 23 23 26 34 48 53 82]]


In [25]:
# 2D array sorting

matrix3 = np.sort(
    [
        [46, 78, 93, 32],
        [45, 4, 57, 33],
        [68, 74, 69, 99]
    ]
)
# print(matrix3)



matrix3_row_wise_sorted = np.sort(matrix3, axis=1)          # Axis = 1 means row-wise sorting or horizontal sorting.
print(matrix3_row_wise_sorted)



matrix3_column_wise_sorted = np.sort(matrix3, axis=0)       # Axis = 0 means column-wise sorting or vertical sorting.
print(matrix3_column_wise_sorted)

[[32 46 78 93]
 [ 4 33 45 57]
 [68 69 74 99]]
[[ 4 33 45 57]
 [32 46 74 93]
 [68 69 78 99]]


# Searching

In [26]:
# Searching in an array
print(array12)

index_of_x = np.where(array12 == 11)                        # It returns the index of the first occurrence of value 11 in the array.
print(index_of_x)


index_of_x_gt = np.where(array12 > 11)                      # It returns the index of all the occurrences of the value greater than 11 in the array.
print(index_of_x_gt)


replacing_of_x = np.where(array12 == 11, 100, array12)      # It replaces all the occurrences of value 11 with 100 in the array.
print(replacing_of_x)

[[82 53  9 34 11 23 48 23 26 12]]
(array([0]), array([4]))
(array([0, 0, 0, 0, 0, 0, 0, 0]), array([0, 1, 3, 5, 6, 7, 8, 9]))
[[ 82  53   9  34 100  23  48  23  26  12]]


In [27]:
# Searching in a matrix
print(matrix3)


index_of_x = np.where(matrix3 == 33)                        # It returns the index of the first occurrence of value 33 in the matrix.
print(index_of_x)


index_of_x_gt = np.where(matrix3 > 50)                      # It returns the index of all the occurrences of the value greater than 50 in the matrix.
print(index_of_x_gt)


replacing_of_x = np.where(matrix3 == 74, 100, matrix3)      # It replaces all the occurrences of value 74 with 100 in the matrix.
print(replacing_of_x)

[[32 46 78 93]
 [ 4 33 45 57]
 [68 69 74 99]]
(array([1]), array([1]))
(array([0, 0, 1, 2, 2, 2, 2]), array([2, 3, 3, 0, 1, 2, 3]))
[[ 32  46  78  93]
 [  4  33  45  57]
 [ 68  69 100  99]]


In [28]:
print(matrix3)

max_value = np.argmax(matrix3)          # It returns the index of the maximum value in the matrix.
print(max_value)


min_value = np.argmin(matrix3)          # It returns the index of the minimum value in the matrix.
print(min_value)

[[32 46 78 93]
 [ 4 33 45 57]
 [68 69 74 99]]
11
4


# Counting
* To learn more, visit this Url: https://numpy.org/doc/2.4/reference/generated/numpy.count_nonzero.html#numpy.count_nonzero

In [29]:
array13 = np.random.randint(0, 100, size=(100, ))  # size = (row, column)
print(array13)

[61 16 74 82 16 91 51 70 69  1 55 32 49 33 31 83 35 78  4 57 42 94 28 59
  5 14 73 53 36 71 32 53 82 92 84 62  7 12  1 95 78  9 36 22 10  2 28 42
 29 65 65 21 26 62  6 15 12 57 91 30 14 46 42 34 49 18 41 22 40 94 10 67
 12 39 10 85 87 67 64 42 15 44 60  4 13 47 90  7 57 88  4 41 89 54 76 32
 39 13 22 86]


In [30]:
# Finding values greater than 50

count_gt50 = np.count_nonzero(array13 > 50)
print(count_gt50)

42


In [31]:
# Finding values greater than 100

count_gt100 = np.count_nonzero(array13 > 100)
print(count_gt100)

0


In [32]:
# Finding the count of values equal to 40

count_eq40 = np.count_nonzero(array13 == 40)
print(count_eq40)

1


In [33]:
# Finding the count of unique values

count_unique = np.unique(array13)
print(count_unique)

[ 1  2  4  5  6  7  9 10 12 13 14 15 16 18 21 22 26 28 29 30 31 32 33 34
 35 36 39 40 41 42 44 46 47 49 51 53 54 55 57 59 60 61 62 64 65 67 69 70
 71 73 74 76 78 82 83 84 85 86 87 88 89 90 91 92 94 95]


In [34]:
# Finding the count of each unique value

count_each_unique = np.unique(array13, return_counts=True)  # It returns first the unique values and then the counts of each unique value.
print(count_each_unique)

(array([ 1,  2,  4,  5,  6,  7,  9, 10, 12, 13, 14, 15, 16, 18, 21, 22, 26,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 39, 40, 41, 42, 44, 46, 47, 49,
       51, 53, 54, 55, 57, 59, 60, 61, 62, 64, 65, 67, 69, 70, 71, 73, 74,
       76, 78, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 94, 95],
      dtype=int32), array([2, 1, 3, 1, 1, 2, 1, 3, 3, 2, 2, 2, 2, 1, 1, 3, 1, 2, 1, 1, 1, 3,
       1, 1, 1, 2, 2, 1, 2, 4, 1, 1, 1, 2, 1, 2, 1, 1, 3, 1, 1, 1, 2, 1,
       2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1]))


# Statistical function

In [35]:
# Loading a csv file
# student_scores = np.genfromtxt('student_scores.csv', delimiter=',')   # Here delimiter represents the way the values are separated
student_scores = np.genfromtxt('student_scores.csv', delimiter=',', skip_header=1)     # Here skip_header represents the number of rows to be skipped from the top.
print(student_scores)

[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [36]:
# Slicing math marks (1st column) from the student_scores array

math_marks = student_scores[:, 0]
print(math_marks)

[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
 62. 95.]


In [37]:
# Finding maximum math mark

math_marks_max = np.max(math_marks)
print(math_marks_max)

95.0


In [38]:
# Finding minimum math mark

math_marks_min = np.min(math_marks)
print(math_marks_min)

45.0


In [39]:
# Finding average math mark

math_marks_average = np.average(math_marks)
print(math_marks_average)

73.15


In [40]:
# Finding median math mark

math_marks_median = np.median(math_marks)
print(math_marks_median)

73.5


In [41]:
# Finding standard deviation of math marks

math_marks_std = np.std(math_marks)
print(math_marks_std)

13.788672887555204


In [42]:
# Finding science marks (2nd column) from the student_scores array

science_marks = student_scores[:, 1]
print(science_marks)

[85. 67. 92. 52. 75. 90. 60. 57. 89. 70. 69. 82. 64. 78. 93. 71. 79. 86.
 63. 97.]


# Correlation Coefficient

* Correlation Coefficient (সহ-সম্পর্ক সহগ) হলো এমন একটি সংখ্যা যা দিয়ে বোঝা যায় দুটি বিষয়ের (Variables) মধ্যে সম্পর্ক কতটা গভীর এবং সেই সম্পর্কটি কোন দিকে যাচ্ছে। সহজ কথায়, একটি বাড়লে অন্যটি বাড়ে কি না, নাকি কমে—সেটাই এটি পরিমাপ করে।

In [43]:
study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])
correlation = np.corrcoef(data)

print("Correlation Matrix:\n", correlation)

Correlation Matrix:
 [[1.         0.99859154]
 [0.99859154 1.        ]]


# Linear algebra

In [44]:
# Matrix multiplication (Dot product).
# Matrix and vector products,
# To learn more, visit: https://www.mathsisfun.com/algebra/matrix-multiplying.html

matrix4 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])


matrix5 = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])


# For dot product of matrix4 and matrix5, we need to make sure that the number of columns of matrix4 must be equal to the number of rows of matrix5.
matrix4_matrix5_dot_product = np.dot(matrix4, matrix5)
print(matrix4_matrix5_dot_product)


# trace
# print(np.trace(B))

[[ 58  64]
 [139 154]]


In [45]:
# Finding trace of a square matrix
matrix6 = np.random.randint(1, 100, size=(4, 4))  # size = (row, column)
print(matrix6)


# Trace of a square matrix is the sum of the elements on the main diagonal.
matrix6_trace = np.trace(matrix6)
print(matrix6_trace)

[[85 88 44 71]
 [50 13  1 15]
 [19 49  1 70]
 [40  5  6 59]]
158


In [46]:
# Finding the determinant of a square matrix,
# To learn more, visit: https://www.mathsisfun.com/algebra/matrix-determinant.html
matrix7 = np.random.randint(1, 10, size=(4, 4))
print(matrix7)


# Determinant of a square matrix is a scalar value. It means that it can be positive or negative.
# Determinant means sum of product of matrix elements along an axis.
matrix7_determinant = np.linalg.det(matrix7)
print(matrix7_determinant)

[[7 5 3 1]
 [8 6 6 3]
 [5 4 1 5]
 [7 8 4 9]]
193.0


In [47]:
# Finding matrix rank,
# To learn more, visit: https://numpy.org/doc/2.4/reference/generated/numpy.linalg.matrix_rank.html

print(matrix7)


matrix7_linalg_rank = np.linalg.matrix_rank(matrix7)
print(matrix7_linalg_rank)

[[7 5 3 1]
 [8 6 6 3]
 [5 4 1 5]
 [7 8 4 9]]
4


# Solution of the DEEP-ML problem: Calculate Mean by Row or Column
Url: https://www.deep-ml.com/problems/4

In [114]:
# This needs to be imported at the top of the file, inside the Deep-ML code writing section.
import numpy as np


def calculate_matrix_mean(matrix: list[list[float]], mode: str) -> list[float]:

    # Initially converting the python list of lists into a numpy array. And at the same time changing the data type of the array into float.
    matrix = np.array(matrix).astype(float)

    # Calculating the mean of the matrix based on the given mode.
    if mode == 'row':
        means = np.mean(matrix, axis=1)
    else:
        means = np.mean(matrix, axis=0)

    # Now converting the numpy array into a list of floats.
    means = means.tolist()

    # Returning the list of means.
    return means


print(calculate_matrix_mean([[1, 2, 3], [4, 5, 6], [7, 8, 9]], 'column'))

[4.0, 5.0, 6.0]


# Solution of the DEEP-ML problem: Matrix-Vector Dot Product
Url: https://www.deep-ml.com/problems/1

In [159]:
# This needs to be imported at the top of the file, inside the Deep-ML code writing section.
import numpy as np


def matrix_dot_vector(a: list[list[int | float]], b: list[int | float]) -> list[int | float]:
    # Return a list where each element is the dot product of a row of 'a' with 'b'.
    # If the number of columns in 'a' does not match the length of 'b', return -1.

    # Initially converting the python list of lists into a numpy array. But we'll not change the data type at this point.
    a = np.array(a)
    b = np.array(b)

    # Checking if the number of columns in 'a' matches the length of 'b'.
    if np.shape(a)[1] != len(b):
        # If not, returning -1.
        return -1
    else:
        # If yes, calculating the dot product of each row of 'a' with 'b'.
        ab_dot_product = np.dot(a, b)

        # Changing the data type of 'ab_dot_product' into int64 only if the data type of 'ab_dot_product' is int64.
        if ab_dot_product.dtype == 'int64':
            ab_dot_product = ab_dot_product.astype(int)

        # Converting the numpy array 'a' into a python list.
        ab_dot_product = ab_dot_product.tolist()

        # Returning the dot product of each row of 'a' with 'b'.
        return ab_dot_product




print(matrix_dot_vector([[1, 2, 3], [2, 4, 5], [6, 8, 9]], [1, 2, 3]))

[14, 25, 49]


# Solution of the DEEP-ML problem: Transpose of a Matrix
Url: https://www.deep-ml.com/problems/2

In [169]:
# This needs to be imported at the top of the file, inside the Deep-ML code writing section.
import numpy as np


def transpose_matrix(a: list[list[int | float]]) -> list[list[int | float]]:
    """
    Transpose a 2D matrix by swapping rows and columns.
    Args:
        a: A 2D matrix of shape (m, n)
    Returns:
        The transposed matrix of shape (n, m)
    """

    # First, converting the python list of lists into a numpy array.
    a = np.array(a)

    # Then transposing the matrix using the numpy function 'transpose'.
    a_transposed = np.transpose(a)

    # Finally, converting the transposed numpy array into a python list of lists.
    a_transposed = a_transposed.tolist()

    # Finally, returning the transposed matrix.
    return a_transposed


print(transpose_matrix([[1, 2], [3, 4], [5, 6]]))

[[1, 3, 5], [2, 4, 6]]


---