# Practice Problem Solution 01

In [1]:
import numpy as np

# Creating a random 1D array
array_1d = np.random.randint(10, size=(10,))     # Values 0 to 10, Rows = 10, Columns = 1
print(array_1d)                                  # Print the array
print(array_1d.shape)                            # Print the shape of the array
print(array_1d.size)                             # Print the total number of elements
print(array_1d.ndim)                             # Print the number of dimensions
print(array_1d.dtype)                            # Print the data type

[9 0 0 4 7 2 1 0 2 3]
(10,)
10
1
int32


In [2]:
# Creating a random 2D array

array_2d = np.random.randint(11, 20, size=(3, 10))      # Values 11 to 20, Rows = 3, Columns = 10
print(array_2d)                                         # Print the array
print(array_2d.shape)                                   # Print the shape of the array
print(array_2d.size)                                    # Print the total number of elements
print(array_2d.ndim)                                    # Print the number of dimensions
print(array_2d.dtype)                                   # Print the data type

[[12 15 17 19 13 18 11 15 13 13]
 [15 18 14 13 18 13 19 11 13 12]
 [11 14 18 19 15 15 17 15 15 13]]
(3, 10)
30
2
int32


In [3]:
# Creating a random 3D array

array_3d = np.random.randint(21, 30, size=(3, 2, 10))       # Values 21 to 30, Depth = 3, Rows = 2, Columns = 10
print(array_3d)                                             # Print the array
print(array_3d.shape)                                       # Print the shape of the array
print(array_3d.size)                                        # Print the total number of elements
print(array_3d.ndim)                                        # Print the number of dimensions
print(array_3d.dtype)                                       # Print the data type

[[[28 27 26 25 29 24 26 24 28 25]
  [28 27 21 21 29 23 23 25 27 28]]

 [[28 29 28 22 23 24 28 28 24 27]
  [27 25 27 23 21 22 28 25 27 28]]

 [[28 28 23 25 23 29 26 27 21 22]
  [23 25 22 26 29 24 21 28 22 23]]]
(3, 2, 10)
60
3
int32


# Practice Problem Solution 02

In [4]:
# Creating an array of zeros of shape (3, 3)

array_zeros = np.zeros((3, 3))
print(array_zeros)
print(array_zeros.shape)
print(array_zeros.size)
print(array_zeros.ndim)
print(array_zeros.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
9
2
float64


In [5]:
# Creating an array of ones of shape (2, 5)

array_ones = np.ones((2, 5))
print(array_ones)
print(array_ones.shape)
print(array_ones.size)
print(array_ones.ndim)
print(array_ones.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(2, 5)
10
2
float64


In [6]:
# Creating a 1D array, filled with 7

array_7_1d = np.full((10,), 7)
print(array_7_1d)
print(array_7_1d.shape)
print(array_7_1d.size)
print(array_7_1d.ndim)
print(array_7_1d.dtype)

[7 7 7 7 7 7 7 7 7 7]
(10,)
10
1
int64


In [7]:
# Creating a 2D array, filled with 7

array_7_2d = np.full((3, 5), 7)
print(array_7_2d)
print(array_7_2d.shape)
print(array_7_2d.size)
print(array_7_2d.ndim)
print(array_7_2d.dtype)

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
(3, 5)
15
2
int64


In [8]:
# Creating a 3D array, filled with 7

array_7_3d = np.full((2, 3, 4), 7)
print(array_7_3d)
print(array_7_3d.shape)
print(array_7_3d.size)
print(array_7_3d.ndim)
print(array_7_3d.dtype)

[[[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]

 [[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]]
(2, 3, 4)
24
3
int64


# Practice Problem Solution 03

In [9]:
# Creating an array of even numbers between 10 and 50, using arrange function

array_even_01 = np.arange(10, 51, 2)
print(array_even_01)
print(array_even_01.shape)
print(array_even_01.size)
print(array_even_01.ndim)
print(array_even_01.dtype)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
(21,)
21
1
int64


In [10]:
# Creating an array of even numbers between 10 and 50, using linspace function

array_even_02 = np.linspace(10, 50, 21)
print(array_even_02)
print(array_even_02.shape)
print(array_even_02.size)
print(array_even_02.ndim)
print(array_even_02.dtype)

[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34. 36. 38. 40. 42. 44.
 46. 48. 50.]
(21,)
21
1
float64


In [11]:
# Creating an array of even numbers between 10 and 50, using the logspace function

array_even_03 = np.logspace(10, 50, 51)             # not possible to get even numbers using logspace
print(array_even_03)

[1.00000000e+10 6.30957344e+10 3.98107171e+11 2.51188643e+12
 1.58489319e+13 1.00000000e+14 6.30957344e+14 3.98107171e+15
 2.51188643e+16 1.58489319e+17 1.00000000e+18 6.30957344e+18
 3.98107171e+19 2.51188643e+20 1.58489319e+21 1.00000000e+22
 6.30957344e+22 3.98107171e+23 2.51188643e+24 1.58489319e+25
 1.00000000e+26 6.30957344e+26 3.98107171e+27 2.51188643e+28
 1.58489319e+29 1.00000000e+30 6.30957344e+30 3.98107171e+31
 2.51188643e+32 1.58489319e+33 1.00000000e+34 6.30957344e+34
 3.98107171e+35 2.51188643e+36 1.58489319e+37 1.00000000e+38
 6.30957344e+38 3.98107171e+39 2.51188643e+40 1.58489319e+41
 1.00000000e+42 6.30957344e+42 3.98107171e+43 2.51188643e+44
 1.58489319e+45 1.00000000e+46 6.30957344e+46 3.98107171e+47
 2.51188643e+48 1.58489319e+49 1.00000000e+50]


# Practice Problem Solution 04

In [12]:
# Creating a 4x4 matrix from 0-15.
array_4x4 = np.arange(16).reshape(4, 4)
print(array_4x4)
print(array_4x4.shape)          # Shape represents the dimensions of the array. The first value is the number of rows, the second value is the number of columns.
print(array_4x4.size)
print(array_4x4.ndim)
print(array_4x4.dtype)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
(4, 4)
16
2
int64


In [13]:
row = array_4x4.shape[0]
col = array_4x4.shape[1]


# Extracting the center matrix from the 4x4 matrix, removing the top and bottom rows and the left and right columns. This is called slicing.
# extracted_center_matrix = array_4x4[1:3, 1:3]
extracted_center_matrix = array_4x4[1:(row-1), 1:(col-1)]
print(extracted_center_matrix)

[[ 5  6]
 [ 9 10]]


# Practice Problem Solution 05

In [14]:
# Creating a random 3x3 array

array_3x3 = np.random.randint(1, 10, size=(3, 3))
print(array_3x3)

[[1 7 3]
 [9 9 5]
 [9 3 8]]


In [15]:
# Another given 1D array is

arrayG = np.array([1, 2, 3])
print(arrayG)
print(arrayG.ndim)

[1 2 3]
1


In [21]:
# Now will add arrayG to each row of array_3x3

array_3x3_result = array_3x3 + arrayG
print(array_3x3_result)

[[ 2  9  6]
 [10 11  8]
 [10  5 11]]


# Practice Problem Solution 06

In [52]:
# Creating a random array from 1 to 10
arrayA = np.arange(1, 11)
print(arrayA)


# Creating another array from 11 to 20
arrayB = np.arange(11, 21)
print(arrayB)


# Calculating the average of the two arrays
arrayC = np.broadcast_arrays((arrayA + arrayB)/2)
print(arrayC)


# Calculating the addition of squares of both arrays
arrayD = np.broadcast_arrays((arrayA ** 2 + arrayB ** 2))
print(arrayD)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
(array([ 6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.]),)
(array([122, 148, 178, 212, 250, 292, 338, 388, 442, 500]),)


---