Open the Anaconda Navigator, select the target environment, and then check if the numpay is installed or not. If not installed, then install it inside the Anaconda Navigator environment and recheck again. After a successful installation now open up PyCharm and check from the paython packages section, there numpy will showup as installed.

In [1]:


arrayA = [1, 2, 3]
print(arrayA * 5)
# The output will be like [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3], which is obviously not what I want.

#----------------------------------------------------------------------------------------------------

import numpy as np

arrayB = np.array([1, 2, 3])
print(arrayB * 5)
# Now the output will be like [ 5 10 15], which is what I actually want. And this is what NumPy can do.

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[ 5 10 15]


# NdArray

In [2]:
# 1d Array
arrayC = np.array([1, 2, 3])
print(arrayC)                   # Array
print(type(arrayC))             # Array Type
print(arrayC.ndim)              # Array Dimensions 1
print(arrayC.shape)             # Array Shape (3, ) 1 Rows and 3 Column
print('-' * 100)

# 2d Array
arrayD = np.array(
    [
        [1, 2, 3],              # Row 1
        [4, 5, 6]               # Row 2
    ]
)
print(arrayD)                   # Array
print(arrayD.ndim)              # Array Dimensions 2
print(arrayD.shape)             # Array Shape (2, 3) 2 Rows and 3 Columns
print('-' * 100)

# 3d Array
arrayE = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6]
        ],
        [
            [7, 8, 9],
            [10, 11, 12]
        ]
    ]
)
print(arrayE)                   # Array
print(arrayE.ndim)              # Array Dimensions 3
print(arrayE.shape)             # Array Shape (2, 2, 3) 2 Layers and 2 Rows and 3 Columns
print('-' * 100)

[1 2 3]
<class 'numpy.ndarray'>
1
(3,)
----------------------------------------------------------------------------------------------------
[[1 2 3]
 [4 5 6]]
2
(2, 3)
----------------------------------------------------------------------------------------------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)
----------------------------------------------------------------------------------------------------


# Array attributes
##### - `ndim`: Number of dimensions
##### - `shape`: Shape of the array
##### - `size`: Total number of elements in the array
##### - `dtype`: Data type of the array elements
##### - `itemsize`: Size in bytes of each element
##### - `nbytes`: Total bytes consumed by the elements of the array

In [3]:
# Dimension
print('Dimensions of the Arrays:')
print(arrayB.ndim)
print(arrayC.ndim)
print(arrayD.ndim)
print(arrayE.ndim)
print('-' * 100)


# Shape
print('Shapes of the Arrays:')
print(arrayB.shape)
print(arrayC.shape)
print(arrayD.shape)
print(arrayE.shape)
print('-' * 100)


# Size
print('Sizes of the Arrays:')
print(arrayB.size)
print(arrayC.size)
print(arrayD.size)
print(arrayE.size)
print('-' * 100)


# Data Type
print('Data types of the Arrays:')
print(arrayB.dtype)
print(arrayC.dtype)
print(arrayD.dtype)
print(arrayE.dtype)
print('-' * 100)

Dimensions of the Arrays:
1
1
2
3
----------------------------------------------------------------------------------------------------
Shapes of the Arrays:
(3,)
(3,)
(2, 3)
(2, 2, 3)
----------------------------------------------------------------------------------------------------
Sizes of the Arrays:
3
3
6
12
----------------------------------------------------------------------------------------------------
Data types of the Arrays:
int64
int64
int64
int64
----------------------------------------------------------------------------------------------------


# ndarray Data Type

In [4]:
arrayF = np.array([1, 2, 3])
print(arrayF.dtype)

arrayG = np.array([1.5, 2.4, 3.2])
print(arrayG.dtype)

int64
float64


In [5]:
arrayH = np.array([1, 2, 3.2])
# upcasted to float
print(arrayH.dtype)

# upcasted to string
arrayI = np.array([1, 2, 3.2, 'hello'])
print(arrayI.dtype)

arrayJ = np.array([1, True, 3.25, 'hello', ])
# upcasted to object
print(arrayJ.dtype)

float64
<U32
<U32


# Selecting a data type for an array, using `dtype` and `astype`

In [6]:
arrayK = np.array([1, 2, 300], dtype=np.int16)  # Change the data type of the array to int16
print(arrayK.dtype)
print(arrayK)

arrayL = arrayK.astype(np.int32)
print(arrayL.dtype)

# This will raise an error because string cannot be converted to float
# arrayM = np.array([1, 2, 3.2, 'hello'], dtype=np.float64)

arrayN = np.array([1, 2, 3.2, True, 'hello'])
print(arrayN.dtype)

int16
[  1   2 300]
int32
<U32


# ndarray creation from existing data

In [7]:
#list
lst = [10, 20, 30, 40, 40.5]
# arrayO = np.array(lst)
arrayO = np.array(lst, dtype=np.int32)
print(arrayO)
print(type(arrayO))
print(arrayO.dtype)
print('-' * 100)




mixed_lst = [10, True, 'Hello']
arr = np.array(mixed_lst)
print(arr)
print(type(arr))
print(arr.dtype)
print('-' * 100)




matrix = [
    [1, 2, 3],
    [4, 5, 6]
]
arrayP = np.array(matrix)
print(arrayP)
print(type(arrayP))
print(arrayP.dtype)
print(arrayP.shape)
print(arrayP.ndim)
print('-' * 100)

[10 20 30 40 40]
<class 'numpy.ndarray'>
int32
----------------------------------------------------------------------------------------------------
['10' 'True' 'Hello']
<class 'numpy.ndarray'>
<U21
----------------------------------------------------------------------------------------------------
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2
----------------------------------------------------------------------------------------------------


In [8]:
#tuple
tpl = (10, 20, 30)


# arrayQ = np.array(tpl)
arrayQ = np.array(tpl, dtype=np.int32)
print(arrayQ.dtype)


arrayR = arrayQ.astype(np.int16)
print(arrayR)
print(type(arrayR))
print(arrayR.dtype)
print(arrayR.shape)
print(arrayR.ndim)

int32
[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1


In [9]:
#set
st = {1, 2, 3}


# arrayS = np.array(st)   # Set cannot be converted to ndarray directly. It needs to be converted to a list first.
arrayS = np.array(list(st))
print(arrayS)
print(type(arrayS))
print(arrayS.dtype)


arrayT = arrayS.astype(np.int16)
print(arrayT)
print(type(arrayT))
print(arrayT.dtype)
print(arrayT.shape)
print(arrayT.ndim)
print(arrayT.size)

[1 2 3]
<class 'numpy.ndarray'>
int64
[1 2 3]
<class 'numpy.ndarray'>
int16
(3,)
1
3


In [10]:
# dictionary
dict = {'a': 10, 'b': 20, 'c': 30}
# print(dict)                             # {'a': 10, 'b': 20, 'c': 30}
# print(type(dict))                       # <class 'dict'>

keys = dict.keys()
# print(keys)                             # dict_keys(['a', 'b', 'c'])

values = dict.values()
# print(values)                           # dict_values([10, 20, 30])

items = dict.items()
# print(items)                            # dict_items([('a', 10), ('b', 20), ('c', 30)])





#keys to ndarray
arrayU = np.array(list(keys))
print(arrayU)
print(type(arrayU))
print(arrayU.dtype)
print(arrayU.shape)
print(arrayU.ndim)
print(arrayU.size)





#values to ndarray
arrayU = np.array(list(values))
print(arrayU)
print(type(arrayU))
print(arrayU.dtype)
print(arrayU.shape)
print(arrayU.ndim)
print(arrayU.size)

arrayU = arrayU.astype(np.int16)
print(arrayU)
print(arrayU.dtype)





#items to ndarray
# arrayU = np.array(items)
arrayU = np.array(list(items))
print(arrayU)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3
[10 20 30]
<class 'numpy.ndarray'>
int64
(3,)
1
3
[10 20 30]
int16
[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3,)
1
3


# Creating ndarray from scratch

In [11]:
# Creating arrays using np.zeros

# arrayV = np.zeros((2,3))
# print(arrayV)
# print(type(arrayV))
# print(arrayV.dtype)
# print(arrayV.shape)
# print(arrayV.ndim)
# print(arrayV.size)


# arrayV = np.zeros((2,3), dtype=np.int8)
# print(arrayV)
# print(type(arrayV))
# print(arrayV.dtype)


# arrayV = np.zeros_like(arrayE)              # It will create an array of zeros with the same shape as arrayE.
# print(arrayV)
# print(arrayV.shape)

In [12]:
# Creating arrays using np.ones

# arrayV = np.ones((2,3))
# print(arrayV)
# print(type(arrayV))
# print(arrayV.dtype)
# print(arrayV.shape)
# print(arrayV.ndim)
# print(arrayV.size)


# arrayV = np.ones((2,3), dtype=np.int8)
# print(arrayV)
# print(type(arrayV))
# print(arrayV.dtype)


# arrayV = np.ones_like(arrayE)              # It will create an array of ones with the same shape as arrayE.
# print(arrayV)
# print(arrayV.shape)

In [13]:
# Creating arrays using np.empty

# arrayW = np.empty((2,3))
# print(arrayW)
# print(type(arrayW))
# print(arrayW.dtype)
# print(arrayW.shape)
# print(arrayW.ndim)
# print(arrayW.size)


# arrayW = np.empty((2,3), dtype=np.int8)
# print(arrayW)
# print(type(arrayW))
# print(arrayW.dtype)


# arrayW = np.empty_like(arrayE)              # It will create an array of emptys with the same shape as arrayE.
# print(arrayW)
# print(arrayW.shape)

In [14]:
# Creating arrays using np.full

# arrayW = np.full((2,3))               # This will raise an error because full requires an initial value.
# arrayW = np.full((2,3), 5)            # The full array will be filled with 5.
# arrayW = np.full((2,3), True)         # The full array will be filled with True.
# arrayW = np.full((2,3), np.inf)         # The full array will be filled with infinity.
# print(arrayW)
# print(type(arrayW))
# print(arrayW.dtype)
# print(arrayW.shape)
# print(arrayW.ndim)
# print(arrayW.size)


# arrayW = np.full((2,3), 5, dtype=np.int8)
# print(arrayW)
# print(type(arrayW))
# print(arrayW.dtype)


# arrayW = np.full_like(arrayE, 9)              # It will create an array of 9 with the same shape as arrayE. The data type will be the same as arrayE.
# arrayW = np.full_like(arrayE, 9.5, dtype=np.float16)              #
# print(arrayW)
# print(arrayW.shape)

# Array creation with random values

In [15]:
# np.random.rand(shape)

# arrayX = np.random.rand(2, 3)  # All values will be randomly in between 0 and 1
# print(arrayX)
# print(type(arrayX))
# print(arrayX.dtype)
# print(arrayX.shape)
# print(arrayX.ndim)
# print(arrayX.size)

In [16]:
# np.random.randint(start, end, shape)

# arrayX = np.random.randint(1, 10, (2, 3))         # All values will be integer, randomly in between 1 and 10
# print(arrayX)
# print(type(arrayX))
# print(arrayX.dtype)
# print(arrayX.shape)
# print(arrayX.ndim)
# print(arrayX.size)

In [17]:
# np.random.uniform(start, end, shape)

# arrayX = np.random.uniform(1, 10, (1, 2, 3))           # All values will be floating, randomly in between 1 and 10
# print(arrayX)
# print(type(arrayX))
# print(arrayX.dtype)
# print(arrayX.shape)
# print(arrayX.ndim)
# print(arrayX.size)

# Array creation with range functions

In [18]:
# np.arange(start, end, step) -> similar to range function

# arrayX = np.arange(1, 10, 2)
# print(arrayX)
# print(type(arrayX))
# print(arrayX.dtype)
# print(arrayX.shape)
# print(arrayX.ndim)
# print(arrayX.size)

In [19]:
# np.arange(start, end, step) -> similar to range function

# arrayX = np.arange(1, 10, 1)
# print(arrayX)

# matrix = arrayX.reshape(3, 3)                     # Creating a 3x3 matrix from the 1D array
# print(matrix)

# print(type(arrayX))
# print(arrayX.dtype)
# print(arrayX.shape)
# print(arrayX.ndim)
# print(arrayX.size)



# matrix = np.arange(1, 10, 1).reshape(3, 3)          # Creating a 3x3 matrix from the 1D array
# print(matrix)

# print(type(matrix))
# print(matrix.dtype)
# print(matrix.shape)
# print(matrix.ndim)
# print(matrix.size)

In [32]:
# np.linspace(start, end(included), count)

# arrayX = np.linspace(1, 10, 1)                  # [1.]
# arrayX = np.linspace(1, 10, 3)                  # [ 1.   5.5 10. ]
# arrayX = np.linspace(0, 10, 5)                  # [ 1.    3.25  5.5   7.75 10.  ]
# arrayX = np.linspace(1, 10, 10)                  # [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
# print(arrayX)
# print(type(arrayX))
# print(arrayX.dtype)
# print(arrayX.shape)
# print(arrayX.ndim)
# print(arrayX.size)

[ 0.   2.5  5.   7.5 10. ]


In [30]:
# np.linspace(start, end(included), count)

# arrayX = np.logspace(0, 4, 5)                  # That is, 5 equally spaced values between 10^0 and 10^4. Here base 10 is used.
arrayX = np.logspace(0, 4, 5, base=2)                  # That is, 5 equally spaced values between 2^0 and 2^4. Here base 2 is used.
print(arrayX)
# print(type(arrayX))
# print(arrayX.dtype)
# print(arrayX.shape)
# print(arrayX.ndim)
# print(arrayX.size)

[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07
 1.00000000e+10]


# Creating matrix for Linear algebra

In [22]:
# Diagonal matrix is a square matrix with all elements on the main diagonal. Rest of the elements are zero.

# diagonal_matrix = np.diag([1, 2, 3])
# diagonal_matrix = np.diag([1, 2, 3, 4])
diagonal_matrix = np.diag([1, 2, 3, 4, 5])
print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]
(5, 5)


In [23]:
# Identity matrix is a matrix with ones on the diagonal and zeros elsewhere.

# identity_mat = np.eye(3)
# identity_mat = np.eye(4)
# identity_mat = np.eye(5)
# print(identity_mat)
# print(identity_mat.shape)


# mat = np.eye(3, 4)
# print(mat)


# mat = np.eye(3, 4, -2)
# mat = np.eye(3, 4, -1)
# mat = np.eye(3, 4, 1)
# mat = np.eye(3, 4, 2)
# mat = np.eye(3, 4, 3)
# print(mat)

# Indexing and slicing

In [24]:
# indexing: Here indexing means selecting a particular element from the array.

print(arrayC)
print(arrayD)

print(arrayC[2])
print(arrayD[1][1])

arrayC[2] = 4
print(arrayC)

arrayD[1][2] = 9
print(arrayD)

[1 2 3]
[[1 2 3]
 [4 5 6]]
3
5
[1 2 4]
[[1 2 3]
 [4 5 9]]


In [25]:
# slicing: Here slicing means selecting a particular range of elements from the array.
# 1d Array = arr[start : end(excluding) : step]

print(arrayC)
arrayC1 = arrayC[0:2].copy()
print(arrayC1)

[1 2 4]
[1 2]


In [26]:
# slicing: Here slicing means selecting a particular range of elements from the array.
# 2d Array = arr[row_start:row_end(excluding):step, column_start:column_end(excluding):step]

arrayD = np.array(
    [
        [8, 6, 6, 1, 5, 5],
        [2, 3, 1, 8, 3, 7],
        [3, 5, 9, 4, 4, 4]
    ]
)
print(arrayD)


slice_row_0 = arrayD[0, ::]             # Slicing the first row of the array
slice_row_1 = arrayD[1, ::]             # Slicing the second row of the array
slice_row_2 = arrayD[2, ::]             # Slicing the third row of the array
# print(slice_row_0)
# print(slice_row_1)
# print(slice_row_2)


slice_col_0 = arrayD[::, 0]          # Slicing the first column of the array
slice_col_1 = arrayD[::, 1]          # Slicing the second column of the array
slice_col_2 = arrayD[::, 2]          # Slicing the third column of the array
slice_col_3 = arrayD[::, 3]          # Slicing the fourth column of the array
# print(slice_col_0)
# print(slice_col_1)
# print(slice_col_2)
# print(slice_col_3)


slice_portion_1 = arrayD[0:3:, 0:3:]
slice_portion_2 = arrayD[0:2:, 1:5:]
# print(slice_portion_1)
# print(slice_portion_2)

[[8 6 6 1 5 5]
 [2 3 1 8 3 7]
 [3 5 9 4 4 4]]


# Advanced Indexing

In [27]:
listA = np.array([10, 20, 30, 40])
values = listA[[0, 3, 1]]
print(values)

[10 40 20]


In [28]:
array2 = np.array(
    [
        [8, 6, 6, 1, 5, 5],
        [2, 3, 1, 8, 3, 7],
        [3, 5, 9, 4, 4, 4]
    ]
)

print(array2)
print(array2[[0, 1], [1, 2]])



# Use of boolean indexing
array2_gt2 = array2[array2 > 2]
print(array2_gt2)



# Array modification using boolean indexing
# array2[array2 > 2] = 0
# print(array2)



# Iterating over 2D arrays
# np.nditer(array2) provides an scaler element, which is a 0-dim NumPy Object. So 'i' is not iterable. Therefore, this expression will give an error.
# for i in np.nditer(array2):
#     for j in i:
#         print(j)


for i in np.nditer(array2):
    print(i)



# Iterating over 2D arrays with index and value
for index, value in np.ndenumerate(array2):
    print("Index:", index, "Value:", value)


[[8 6 6 1 5 5]
 [2 3 1 8 3 7]
 [3 5 9 4 4 4]]
[6 1]
[8 6 6 5 5 3 8 3 7 3 5 9 4 4 4]
8
6
6
1
5
5
2
3
1
8
3
7
3
5
9
4
4
4
Index: (0, 0) Value: 8
Index: (0, 1) Value: 6
Index: (0, 2) Value: 6
Index: (0, 3) Value: 1
Index: (0, 4) Value: 5
Index: (0, 5) Value: 5
Index: (1, 0) Value: 2
Index: (1, 1) Value: 3
Index: (1, 2) Value: 1
Index: (1, 3) Value: 8
Index: (1, 4) Value: 3
Index: (1, 5) Value: 7
Index: (2, 0) Value: 3
Index: (2, 1) Value: 5
Index: (2, 2) Value: 9
Index: (2, 3) Value: 4
Index: (2, 4) Value: 4
Index: (2, 5) Value: 4


---